AWSTemplateVersion: '2010-09-09'
Description: s3 bucket for our CICD PR

Parameters:
  Environment:
    Type: String
    Default: test
    AllowedValues:
      - test
      - staging
      - production

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-${Environment}-bucket'
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Environment
          Value: GithubActionsTesting
        - Key: Owner
          Value: LambdaWorkflows

Outputs:
  BucketName:
    Description: 'The name of the S3 bucket'
    Value: !Ref MyS3Bucket