name: Deploy AWS Lambda Function # name of the workflow, which will be displayed in the Actions tab of your repository

on:
  push: # defines the events that will trigger the workflow (push, pull_request, etc.)
    branches: # specify the branch to trigger the workflow on
      - main # specify the branch to trigger the workflow on
    paths:
      - 'lambda/' # specify the path to trigger the workflow on

jobs: # defines the jobs that will run when the workflow is triggered
  deploy_lambda: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # checks out the repository to the runner

      - name: set up Python # sets up the Python environment using the specified version
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' # specify the Python version to use

      - name: install dependencies # installs the dependencies specified in the requirements.txt file
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -t lambda/

      - name: Configure AWS Credentials # congigures the AWS credentials using the AWS access key ID and secret access key stored in the repository secrets
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} # specify the AWS access key ID from the repository secrets
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # specify the AWS secret access key from the repository secrets
          aws-region: us-east-2 

      - name: Deploy Lambda Function 
        run: |
         cd Lambda
         zip -r function.zip . 
         aws lambda update-function-code --function-name my-lambda-function --zip-file fileb://function.zip 