name: Deploy AWS Lambda

on:
  push:
    branches:
      - main
    paths:
      - 'Lambda/**'

  jobs: 
    deploy-lambda: # Name of the job
      runs-on: unbuntu-latest # Use Ubuntu as the runner environment
      steps:
        - uses: actions/checkout@v2
      
        - name: Set up Python # Set up Python environment
          uses: actions/setup-python@v2
          with:
            python-version: '3.8'

        - name: Install dependencies # Install dependencies from requirements.txt into Lambda directory
          run: 
            python -m pip install --upgrade pip
            pip install -r Lambda/requirments.txt -t lambda/

        - name: Configure AWS Creds # Set up AWS Credentials to allow deployment to Lambda
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1

        - name: Deploy Lambda function #Zips Lambda Directory and updates Lambda Function 
          run: 
            cd Lambda
            zip -r lambda_function.zip .
            aws lambda update-function-code --function-name MyTestCICDLabmda --zip-file fileb://lambda_function.zip